### ISSUE TITLE
obspy-runtests not working on python 2.5 anymore

### ISSUE THREAD

**Issue by trac2github** [obspy/obspy#323]
Due to an unavilable import from collections, `obspy-runtests` is not working anymore on Python 2.5:
{{{
# !python

(local)user@lenny:~/obspy/trunk/misc/scripts$ obspy-runtests
Traceback (most recent call last):
  File "/home/user/local/bin/obspy-runtests", line 8, in <module>
    load_entry_point('obspy.core==0.6.0.dev-r3252', 'console_scripts', 'obspy-runtests')()
  File "/usr/lib/python2.5/site-packages/pkg_resources.py", line 318, in load_entry_point

  File "/usr/lib/python2.5/site-packages/pkg_resources.py", line 2221, in load_entry_point

  File "/usr/lib/python2.5/site-packages/pkg_resources.py", line 1954, in load
    "EntryPoint must be in 'name=module:attrs [extras]' format",
  File "/home/user/obspy/trunk/obspy.core/obspy/core/**init**.py", line 78, in <module>
    from obspy.core.util.base import _getVersionString
  File "/home/user/obspy/trunk/obspy.core/obspy/core/util/__init__.py", line 14, in <module>
    from obspy.core.util.base import NamedTemporaryFile, add_doctests, \
  File "/home/user/obspy/trunk/obspy.core/obspy/core/util/base.py", line 12, in <module>
    from obspy.core.util.ordereddict import OrderedDict
  File "/home/user/obspy/trunk/obspy.core/obspy/core/util/ordereddict.py", line 8, in <module>
    from collections import MutableMapping
ImportError: cannot import name MutableMapping
}}}
