### ISSUE TITLE
python 3.10 Mapping import change

### ISSUE THREAD

**Issue by filefolder** [obspy/obspy#2975]
just noticing that from 3.10 this import needs to be changed [ref](https://stackoverflow.com/questions/69381312/in-vs-code-importerror-cannot-import-name-mapping-from-collections)

`from collections import Mapping`  > `from collections.abc import Mapping`

```
ERROR io/json/tests/test_json.py - ImportError: cannot import name 'Mapping' ...
ERROR io/pde/tests/test_mchedr.py - ImportError: cannot import name 'Mapping'...
ERROR io/quakeml/core.py - ImportError: cannot import name 'Mapping' from 'co...
ERROR io/quakeml/tests/test_quakeml.py - ImportError: cannot import name 'Map...
ERROR io/seiscomp/core.py - ImportError: cannot import name 'Mapping' from 'c...
ERROR io/seiscomp/event.py - ImportError: cannot import name 'Mapping' from '...
ERROR io/seiscomp/tests/test_core.py - ImportError: cannot import name 'Mappi...
ERROR io/seiscomp/tests/test_event.py - ImportError: cannot import name 'Mapp...
```

happy to roll this into the seiscomp PR but not sure what the best way to do this is, suggestions very welcome

**Comment by QuLogic** [comment]
Better to make a separate PR; there are files other than `seiscomp` listed there.

**Comment by filefolder** [comment]
is there a style guide for this type of conditional import? otherwise i would default to something like

```
try:
    from collections import Mapping
except ImportError:
    from collections.abc import Mapping
```

**Comment by d-chambers** [comment]
Does 

> from collections.abc import Mapping

Work with python 3.7?

**Comment by filefolder** [comment]
good question, I suspect so but I don't have anything lower than 3.8 anywhere.

it seems that the distinct "collections.abc" has been around since 3.3 so i would guess this has been the correct method ever since. is the plan to drop 2.7 support completely?

**Comment by QuLogic** [comment]
Python 2 support is already gone, so you should be able to just change the imports over.

**Comment by filefolder** [comment]
looks like this was addressed already (in 2019!) but had been toggled on/off/on again. will PR if necessary but looks like ready to go for 1.3
