### ISSUE TITLE
Station plot not working

### ISSUE THREAD

**Issue by trichter** [obspy/obspy#2097]
I am working with Obspy master, matplotlib 2.2.2 via conda-forge.

Problem seems to be `Normalize` which expects numbers but gets strings.

```
In [1]: read_inventory().plot()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/anaconda/envs/workhorse/lib/python3.6/site-packages/matplotlib/colors.py in _sanitize_extrema(ex)
    100     try:
--> 101         ret = np.asscalar(ex)
    102     except AttributeError:

~/anaconda/envs/workhorse/lib/python3.6/site-packages/numpy/lib/type_check.py in asscalar(a)
    479     """
--> 480     return a.item()
    481 

AttributeError: 'str' object has no attribute 'item'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-1-fc509fcc3356> in <module>()
----> 1 read_inventory().plot()

~/dev/obspy/obspy/core/inventory/inventory.py in plot(self, projection, resolution, continent_fill_color, water_fill_color, marker, size, label, color, color_per_network, colormap, legend, time, show, outfile, method, fig, **kwargs)
    888                        water_fill_color=water_fill_color,
    889                        colormap=None, colorbar=False, marker=marker,
--> 890                        title=None, show=False, fig=fig, **kwargs)
    891 
    892         if legend is not None and color_per_network:

~/dev/obspy/obspy/imaging/maps.py in plot_map(method, *args, **kwargs)
    763     if method is None:
    764         if HAS_BASEMAP:
--> 765             return plot_basemap(*args, **kwargs)
    766         elif HAS_CARTOPY:
    767             return plot_cartopy(*args, **kwargs)

~/dev/obspy/obspy/imaging/maps.py in plot_basemap(lons, lats, size, color, labels, projection, resolution, continent_fill_color, water_fill_color, colormap, colorbar, marker, title, colorbar_ticklabel_format, show, fig, **kwargs)
    177         datetimeplot = False
    178 
--> 179     scal_map = ScalarMappable(norm=Normalize(min_color, max_color),
    180                               cmap=colormap)
    181     scal_map.set_array(np.linspace(0, 1, 1))

~/anaconda/envs/workhorse/lib/python3.6/site-packages/matplotlib/colors.py in __init__(self, vmin, vmax, clip)
    890         *clip* = *False*.
    891         """
--> 892         self.vmin = _sanitize_extrema(vmin)
    893         self.vmax = _sanitize_extrema(vmax)
    894         self.clip = clip

~/anaconda/envs/workhorse/lib/python3.6/site-packages/matplotlib/colors.py in _sanitize_extrema(ex)
    101         ret = np.asscalar(ex)
    102     except AttributeError:
--> 103         ret = float(ex)
    104     return ret
    105 

ValueError: could not convert string to float: '#b15928'
```

**Comment by krischer** [comment]
This is dealt with in #2089 which unfortunately is not yet merged.
