### ISSUE TITLE
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

### ISSUE THREAD

**Issue by FSet89** [obspy/obspy#2958]
- Version 1.2.2, python 3.9, Raspbian OS
- numpy version 1.18
- installed with pip

when i import obspy i get this error:

**RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
File "/home/pi/venv-test-2/lib/python3.9/site-packages/obspy/__init__.py", line 44, in <module>
    from obspy.core.event import read_events, Catalog
  File "/home/pi/venv-test-2/lib/python3.9/site-packages/obspy/core/event/__init__.py", line 30, in <module>
    from .catalog import Catalog, read_events
  File "/home/pi/venv-test-2/lib/python3.9/site-packages/obspy/core/event/catalog.py", line 40, in <module>
    from .event import Event
  File "/home/pi/venv-test-2/lib/python3.9/site-packages/obspy/core/event/event.py", line 30, in <module>
    from obspy.imaging.source import plot_radiation_pattern, _setup_figure_and_axes
  File "/home/pi/venv-test-2/lib/python3.9/site-packages/obspy/imaging/source.py", line 26, in <module>
    from obspy.imaging.mopad_wrapper import beach
  File "/home/pi/venv-test-2/lib/python3.9/site-packages/obspy/imaging/mopad_wrapper.py", line 31, in <module>
    import matplotlib.collections as mpl_collections
  File "/home/pi/venv-test-2/lib/python3.9/site-packages/matplotlib/collections.py", line 17, in <module>
    from . import (_path, artist, cbook, cm, colors as mcolors, docstring,
ImportError: numpy.core.multiarray failed to import**

However I can correctly import matplotlib.

**Comment by ThomasLecocq** [comment]
did you change the numpy version _after_ installing obspy from source ?

**Comment by FSet89** [comment]
Actually I tried different versions because I did not manage to make it work. With the latest numpy release I get:

**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.9/site-packages/obspy/__init__.py", line 39, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/home/pi/.local/lib/python3.9/site-packages/obspy/core/__init__.py", line 124, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/home/pi/.local/lib/python3.9/site-packages/obspy/core/utcdatetime.py", line 27, in <module>
    from obspy.core.util.deprecation_helpers import ObsPyDeprecationWarning
  File "/home/pi/.local/lib/python3.9/site-packages/obspy/core/util/__init__.py", line 27, in <module>
    from obspy.core.util.base import (ALL_MODULES, DEFAULT_MODULES,
  File "/home/pi/.local/lib/python3.9/site-packages/obspy/core/util/base.py", line 36, in <module>
    from obspy.core.util.misc import to_int_or_zero, buffered_load_entry_point
  File "/home/pi/.local/lib/python3.9/site-packages/obspy/core/util/misc.py", line 214, in <module>
    loadtxt(np.array([0]), ndmin=1)
  File "/home/pi/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 1086, in loadtxt
    ncols = len(usecols or split_line(first_line))
  File "/home/pi/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 977, in split_line
    line = line.split(comment, 1)[0]
AttributeError: 'numpy.int32' object has no attribute 'split'**

In fact, after upgrading numpy, I could import obspy. Then I installed another package (pyserial). On the second attempt, I got this error when importing obspy.

**Comment by ThomasLecocq** [comment]
Currently obspy doesn't work with numpy 1.22, so 1.21 will work. Indeed , of you install other packages, make sure you don't upgrade numpy simultaneously. Alternatively, you can install obspy from source, using the master branch here

**Comment by FSet89** [comment]
With numpy 1.21 I get the original error. I tried to downgrade matplotlib but then I get another error from scipy.

**Comment by d-chambers** [comment]
Did you try installing obspy from source?
```bash
python -m pip install git+https://github.com/obspy/obspy
```
