### PR TITLE
Python 3.13 & 3.14 - futureproof signal.polarization for ODR - complex numbers - codec removal

### PR DESCRIPTION
**Pull request by ThomasLecocq**
### What does this PR do?

It tests the default tests on py 3.13 & 3.14 , and the network tests on 3.14 (for now)

### Why was it initiated?  Any relevant Issues?

Let's use this temporarily to check future problems/incompatibilities.

Linked to #3649 for example.

### PR Checklist
- [x] Correct base branch selected? `master` for new features, `maintenance_...` for bug fixes
- [x] If all tests including network modules (e.g. `clients.fdsn`) should be tested for the PR,
      just add the `test_network` tag to this PR.
- [x] All tests still pass.
- [x] Any new or changed features are fully documented.
- [x] Significant changes have been added to `CHANGELOG.txt` .
- [x] Add the yellow `ready for review` label when you are ready for the PR to be reviewed.

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
@filefolder your new sandbox :-)

**Comment by filefolder** [comment]
quick notes on 3.14 since 3.13 seems fine. both look perfectly usable outside of the tests

1) `complex(0, 0j)` needs to be `complex(0, 0)` (both give 0j)

(which is the source of the issue in `test_reconstructing_stage_0_from_other_blockettes`)

2) this seems like an excessive volume of warnings / needs syntax update
```
clients/nrl/tests/test_nrl.py: 1072 warnings
  /home/pickle/.local/lib/python3.14/site-packages/obspy/clients/nrl/client.py:562: DeprecationWarning: codecs.open() is deprecated. Use open() instead.
    with codecs.open(path, mode='r', encoding='UTF-8') as f:
```

3) this function in `test_mseed_special_issues` seems to be causing a stink re: signal.SIGKILL for reasons not especially clear

```
    def test_infinite_loop(self, testdata):
        """
        Tests that libmseed doesn't enter an infinite loop on buggy files.
        """
        filename = testdata['infinite-loop.mseed']

        process = multiprocessing.Process(target=_test_function,
                                          args=(filename, ))
        process.start()
        process.join(60)

        fail = process.is_alive()
        process.terminate()
        if process.is_alive():
            if platform.system() == 'Windows':
                os.kill(process.pid, signal.CTRL_BREAK_EVENT)
            else:
                os.kill(process.pid, signal.SIGKILL)
        assert not fail

```
```
  File "/opt/cluster/software/python3/3.14/lib/python3.14/multiprocessing/forkserver.py", line 16, in <module>
    from . import resource_tracker
  File "/opt/cluster/software/python3/3.14/lib/python3.14/multiprocessing/resource_tracker.py", line 30, in <module>
    _IGNORED_SIGNALS = (signal.SIGINT, signal.SIGTERM)
                        ^^^^^^^^^^^^^
AttributeError: module 'signal' has no attribute 'SIGINT' (consider renaming '/home/pickle/.local/lib/python3.14/site-packages/obspy/signal/__init__.py' since it has the same name as the standard library module named 'signal' and prevents importing that standard library module)
```

**Comment by filefolder** [comment]
some network timeouts and the usual codecov headache but that should do it. for last issue there was a bit of an overlap between python's `signal` and obspy's `signal` but workaround works

**Comment by filefolder** [comment]
note that ubuntu-latest py3.12 + will now fail due to #3676

**Comment by ThomasLecocq** [comment]
@filefolder : now that I'm preparing 1.5.0, just noticing we need to check/get your changes here into master (and make sure they pass on 3.8+ too :-) )

**Comment by filefolder** [comment]
Held up by that scipy.odr thing. I think for expediency probably best to just hide the warnings for now and figure out a proper solution for 1.6.

**Comment by ThomasLecocq** [comment]
I think we can afford to put the import inside the method, and if it fails for both the old and new package name, raise ?

**Comment by filefolder** [comment]
I guess what I am trying to avoid for the moment is adding a new dependency since there are probably angles to this I am not considering and time is short.

Should we simply _advise_ users install the package themselves if they're using scipy >= 0.19?

**Comment by ThomasLecocq** [comment]
Right, yes, I think that was the idea of @megies  ; but on the long run we can still check for scipy or the other package, without making it a fixed dependency

**Comment by filefolder** [comment]
gave it a shot, was a bit more complex than I was planning on naturally

**Comment by ThomasLecocq** [comment]
I'm re-adding the 3.8-3.12 tests too, so we can check if all the proposed changes are safe for ALL versions

File: obspy/signal/polarization.py [hunk 1]
```diff
@@ -328,6 +327,28 @@ def particle_motion_odr(stream, noise_thres=0):
     :type noise_thres: float
     :returns: azimuth, incidence, error of azimuth, error of incidence
     """
+
+    # scipy dropping ODR in 1.19, new package not a perfect replacment
+    from importlib.metadata import version
```
Comment (ThomasLecocq) [inline obspy/signal/polarization.py]: maybe opening a can of worms here: but should we make a beauuuuuutiful big PR on using `packaging` and `packaging.Version` for version comparisons ?

Comment (ThomasLecocq) [reply obspy/signal/polarization.py]: @QuLogic you suggested that back in the importlib PR

**Comment by ThomasLecocq** [comment]
congratulations @filefolder , looks like most of the tests pass :-)

File: obspy/signal/polarization.py (hunk 1 above)
Comment (filefolder) [reply obspy/signal/polarization.py]: packaging is probably best practice, in this case i figured importlib had a bit less overhead and we can safely assume the scipy versioning structure. happy to change it

**Comment by ThomasLecocq** [comment]
I merged the github action from master into this, the test matrix is going to be huge, but at least we'll know if we can merge this into master and move on! good night!

**Comment by d-chambers** [comment]
Hey @ThomasLecocq, for multiple reasons, not the least that it will be kinder to the CI, shouldn't we drop the python versions that are passed EoL (eg 3.8 and 3.9, see [here](https://devguide.python.org/versions/))

**Comment by ThomasLecocq** [comment]
Agree and don't want to agree. This version is (surprisingly) very compatible... So refusing older version might sound rude. But allowing them might sound like an encouragement to keep going... And force us to bugfix/backport? No. I feel we can release 1.5.0 with max tolerance, then plan 1.6.0 fast with reduced tolerance (3 or 4 max versions) ... We need to be AND tolerant AND pragmatic with the releases and the concept of long term versions. If we release minor/major versions often, we can manage.

**Comment by filefolder** [comment]
i'm very happy we managed to keep 3.8 in.. and it wasn't too difficult. maybe not intuitive but there are a lot of old data servers out there (and at least a few in our building) that are still very much in use. 

if possible would be great to even keep <3.10 for 1.6 but just drop testing/official support. anyhoo..

File: obspy/signal/polarization.py (hunk 1 above)
Comment (filefolder) [reply obspy/signal/polarization.py]: i just changed it to packaging.Version to be done with it. plus i misspelled replacement and it was bugging me

Comment (claudiodsf) [reply obspy/signal/polarization.py]: A new typo? `ccipy` 😜

Comment (filefolder) [reply obspy/signal/polarization.py]: ay yi yi

**Comment by ThomasLecocq** [comment]
is `packaging` a default builtin py package ? or needs to be added to the requirements ?

**Comment by claudiodsf** [comment]
> is `packaging` a default builtin py package ? or needs to be added to the requirements ?

It should be added as dependency: https://packaging.pypa.io/

**Comment by claudiodsf** [comment]
> > is `packaging` a default builtin py package ? or needs to be added to the requirements ?
> 
> It should be added as dependency: https://packaging.pypa.io/

But, in practice, it's always installed for us, since it's a dependency of Matplotlib: https://github.com/matplotlib/matplotlib/blob/main/pyproject.toml

File: obspy/io/mseed/tests/test_mseed_special_issues.py
Comment (ThomasLecocq) [inline obspy/io/mseed/tests/test_mseed_special_issues.py:1]: this is the only scary/complex change (to me) - Not sure it's desirable to force spawn/fork ; this should be handled at the OS level, not within the code?

File: obspy/signal/polarization.py (hunk 1 above)
Comment (ThomasLecocq) [reply obspy/signal/polarization.py]: typo still pending

File: obspy/signal/polarization.py [hunk 2]
```diff
@@ -340,28 +362,46 @@ def particle_motion_odr(stream, noise_thres=0):
...
     r = np.sqrt(n ** 2 + e ** 2)
 
-    data = scipy.odr.Data(r, abs(z))
-    model = scipy.odr.Model(fit_func)
-    odr = scipy.odr.ODR(data, model, beta0=[1.0])
-    out = odr.run()
-    in_slope = out.beta[0]
-    in_error = out.sd_beta[0]
+    def fit_func(beta, x):
+        # XXX: Eventually this is correct: return beta[0] * x + beta[1]
```
Comment (ThomasLecocq) [inline obspy/signal/polarization.py]: what does this mean ?

File: CHANGELOG.txt [hunk 3]
```diff
@@ -128,6 +128,8 @@ Changes:
      numpy 2.4.0 deprecation expiration. (see #3668)
    * Add warnings.catch_warnings for spectral_estimation tests, linked to
      a new numpy 2.4.0 deprecation. (see #3668)
+   * Prep SciPy dropping ODR for polarization.partical_motion_odr, prompt user
```
Comment (ThomasLecocq) [inline CHANGELOG.txt:157]: reference to 3662 too ?

File: obspy/core/util/obspy_types.py
Comment (ThomasLecocq) [inline obspy/core/util/obspy_types.py:1]: I don't understand what this does? There is no check for py>=3.14 , so it's always applied? 

Side note: is this code part covered with tests?

File: obspy/signal/polarization.py (hunk 2 above)
Comment (filefolder) [reply obspy/signal/polarization.py]: beats me, that was in there before

File: obspy/io/mseed/tests/test_mseed_special_issues.py
Comment (filefolder) [reply obspy/io/mseed/tests/test_mseed_special_issues.py:1]: open to suggestions

Comment (ThomasLecocq) [reply obspy/io/mseed/tests/test_mseed_special_issues.py:1]: I mean , it's just a test case, it doesn't really matter - If it were in the main code and calls, I'd be more scared. Doesn't really matter here.

File: obspy/core/util/obspy_types.py
Comment (filefolder) [reply obspy/core/util/obspy_types.py:1]: tbh i don't know if this is tested anywhere explicitly, but there were certainly a lot of failures in 3.14 before that catch. 

the catch doesn't need a version check, just a safety catch for 3.14 explicitly. the comment is too vague, i will expand on it

File: obspy/signal/polarization.py [hunk 4]
```diff
@@ -328,6 +327,29 @@ def particle_motion_odr(stream, noise_thres=0):
     :type noise_thres: float
     :returns: azimuth, incidence, error of azimuth, error of incidence
     """
+
+    # scipy removing ODR in 1.19.0, new package not a drop-in replacement
+    from importlib.metadata import version
+    from packaging.version import Version
+    scipy_ver = Version(version("scipy"))
```
Comment (megies) [inline obspy/signal/polarization.py]: we have helpers for the main deps: `from obspy.core.util.base import SCIPY_VERSION`

Comment (megies) [reply obspy/signal/polarization.py]: these are simple lists of three items '[major, minor, bugfix version]' and I think all 'post' version stuff is stripped, which should work fine for most comparisons and make them easy

Comment (ThomasLecocq) [reply obspy/signal/polarization.py]: on it

Comment (filefolder) [reply obspy/signal/polarization.py]: guess you're already seeing it but:

`FAILED signal/tests/test_polarization.py::TestPolarization::test_polarization_pm - TypeError: '<' not supported between instances of 'list' and 'tuple'`

**Comment by ThomasLecocq** [comment]
Happy with this one :-)

File: .github/workflows/build_wheels.yml [hunk 5]
```diff
@@ -30,18 +30,13 @@ jobs:
...
         exclude:
-          - build: cp38
-            exclude-flag: true
-          - build: cp39
-            exclude-flag: true
-          - build: cp310
-            exclude-flag: true
           - build: cp311
             exclude-flag: true
+          # Need to repeat for 312, 313, 314?
```
Comment (ThomasLecocq) [inline .github/workflows/build_wheels.yml]: @megies check here

Comment (megies) [reply .github/workflows/build_wheels.yml]: If I understand correctly, these excludes apply to the above mentioned exclude-flag, meaning that if it's a push to master, it will only test building wheels for the latest python (which is not listed in these "excludes"), see comment above under "strategy".
But I'm just assuming that's what's going on.
